export { variables } from '@/styles/abstracts/variables'
export { reset } from '@/styles/base/reset'
export { fonts } from '@/styles/base/fonts'
export { theme } from '@/styles/base/theme'
export { GlobalStyle } from '@/styles/base/global'
